### ISSUE TITLE
建议在github上开通一个打赏通道

### ISSUE THREAD

**Issue by ldmax** [datawhalechina/joyful-pandas#10]
非常赞非常用心的教程，比Python for Data Analysis深入清晰很多，看得出花了很多时间。
希望开通一个打赏通道，表示一下赞赏。
希望Datawhale团队继续做出好的教程。

**Comment by GYHHAHA** [comment]
你好，感谢对本教程的认可！
目前没有计划开通打赏通道，读者的鼓励和获得感是对我们最好的打赏！
Datawhale团队会继续做出好的教程，欢迎持续关注哦！

**Comment by ldmax** [comment]
> 你好，感谢对本教程的认可！
> 目前没有计划开通打赏通道，读者的鼓励和获得感是对我们最好的打赏！
> Datawhale团队会继续做出好的教程，欢迎持续关注哦！

好的，祝Datawhale做出更多好的成果~那我关issue了~
