### ISSUE TITLE
Joyful pandas

### ISSUE THREAD

**Issue by Andyang92** [datawhalechina/joyful-pandas#13]

**Comment by bobfang1992** [comment]
为啥老是有这种傻【X】开issue然后也不说话。。。。。

**Comment by jfjjx** [comment]
跟10万个为什么一样，撒泡尿照照自己的猴样就知道了为啥

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 bobfang1992
发送时间: 2020年9月16日 0:58
收件人: datawhalechina/joyful-pandas
抄送: Subscribed
主题: Re: [datawhalechina/joyful-pandas] Joyful pandas (#13)

 

为啥老是有这种傻【X】开issue然后也不说话。。。。。
