### ISSUE TITLE
Will you update this tutorial?

### ISSUE THREAD

**Issue by albertandking** [datawhalechina/joyful-pandas#2]
Will you update this tutorial?

**Comment by GYHHAHA** [comment]
I'll make the update in April 9 or 10.

**Comment by GYHHAHA** [comment]
1) Some bugs relating chapter 6 and 7 are fixed in Pandas 1.0.2, thus these sections require a little change.
2) I'll adjust the structure for chapter 9 and also give possible solutions for exercise in this chapter.
3) Another example will be added into chapter 10.

**Comment by albertandking** [comment]
Thanks for your reply.
It's a awesome work for us
