### ISSUE TITLE
#1.3.5 Ex5：连续整数的最大长度

### ISSUE THREAD

**Issue by BlueLumen** [datawhalechina/joyful-pandas#20]
![JB7TQQQ7JVA_IKF8F )~ S6](https://user-images.githubusercontent.com/73470293/132029170-83f8a0a3-fec4-47a4-9598-9a37ecbe0dea.png)

通过纸笔演算终于解决了这一行简短的代码所蕴含的奥秘，还是想请问作者，是如何想到的这种奇妙的方法？利用np.nonzero，np.diff，完成了一场代码之间的神奇的化学反应。请问这是某种算法嘛，因为从中好像能体会到一些算法的技巧，如果是这样的，想知道这是哪一种算法或者某类典型问题。感谢！

**Comment by GYHHAHA** [comment]
emmm，当时大概是看np.nonzero文档的时候就想到可以出这个题，其实这个方法从算法设计上是很差的，因为数组需要遍历3次，但显然用一个临时变量记录最大长度来遍历1遍数组就能得到结果了，如果你用c语言写出来测一下的话，速度肯定是会超掉numpy的，这里只是说明一下diff和nonzero的基本用法，帮助巩固。

**Comment by BlueLumen** [comment]
> emmm，当时大概是看np.nonzero文档的时候就想到可以出这个题，其实这个方法从算法设计上是很差的，因为数组需要遍历3次，但显然用一个临时变量记录最大长度来遍历1遍数组就能得到结果了，如果你用c语言写出来测一下的话，速度肯定是会超掉numpy的，这里只是说明一下diff和nonzero的基本用法，帮助巩固。

收到！看到“算法设计、遍历数组”与“临时变量记录最大长度”，思路瞬间又扩展了许多。喜欢这种豁然开朗的感觉（joyful. jpg)。感谢回复。
