### ISSUE TITLE
在pandas的agg函数中使用：NameAgg

### ISSUE THREAD

**Issue by Leo-Ji2020** [datawhalechina/joyful-pandas#22]
新版本pandas在agg函数中增加了新的使用方式，即：agg(  varname=pd.NameAgg(column='', aggfunc='') )
https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html

**Comment by GYHHAHA** [comment]
API中未包含pd.NamedAgg，暂不考虑
