### ISSUE TITLE
pandas(1)

### ISSUE THREAD

**Issue by fanfanw** [datawhalechina/joyful-pandas#3]
import pandas as pd
import numpy as np

- 

1. csv
df = pd.read_csv('data/table.csv')
df.head()
2.txt
df_txt = pd.read_table('data/table.txt') 
df_txt
3.xls
df_excel = pd.read_excel('data/table.xlsx')

- 

1.csv
df.to_csv('data/new_table.csv')
2.
df.to_excel('data/new_table2.xlsx', sheet_name='Sheet1')

data

1. series (values,index,name, type)
s = pd.Series(np.random.randn(5),index=['a','b','c','d','e'],name='这是一个Series',dtype='float64')
s
2. dataframe
df = pd.DataFrame({'col1':list('abcde'),'col2':range(5,10),'col3':[1.3,2.5,3.6,4.6,5.8]},
                 index=list('一二三四五'))
df

- function
df.head()
df.tail()
nunique()
unique()
.count()
.value_counts()

**Comment by GYHHAHA** [comment]
你好，请问你是datawhale组队学习打卡的吗？打卡需要在其他地方（csdn或自己的git仓库）进行哦，谢谢！
