### ISSUE TITLE
网页无法打开

### ISSUE THREAD

**Issue by zyh778** [datawhalechina/joyful-pandas#31]
![image](https://github.com/datawhalechina/joyful-pandas/assets/96773592/692a21a7-65ae-497f-a2d2-e3b2e7cb878d)
网页无法打开

**Comment by GYHHAHA** [comment]
将在本月底前修复

**Comment by GYHHAHA** [comment]
目前把仓库下载到本地，然后打开docs/index.html和线上是一样的效果

**Comment by GYHHAHA** [comment]
@zyh778 你好，现在请使用http://inter.joyfulpandas.datawhale.club/ 这个网址，谢谢
