### ISSUE TITLE
第二章练习二pokemon最后一问

### ISSUE THREAD

**Issue by ChenyangRan** [datawhalechina/joyful-pandas#6]
答案中给出的求解均值比较：
```python
for i in attribute.index.unique()[:-1]:
    temp = attribute.loc[i,:].mean()
    if temp[0] > max_value:
```
对比的是attribute从开始到倒数第二个
另外当我改成
```python
for i in attribute.index.unique():
```
报错**invalid index to scalar variable.**
不知道是我理解的是否正确，恳请指教与给出正确的答案。

**Comment by GYHHAHA** [comment]
请下载最新版的答案，已经修复了这个问题。
“invalid index to scalar variable.”这个报错是因为妖精系的神兽只有1只，所以mean算均值的时候是一个float类型的，其他属性都是可迭代类型，所以temp[0]当temp为float时就报错了。

**Comment by ChenyangRan** [comment]
> 请下载最新版的答案，已经修复了这个问题。
> “invalid index to scalar variable.”这个报错是因为妖精系的神兽只有1只，所以mean算均值的时候是一个float类型的，其他属性都是可迭代类型，所以temp[0]当temp为float时就报错了。

谢谢回答！
