### ISSUE TITLE
问题是否有参考答案？

### ISSUE THREAD

**Issue by linyuhuan** [datawhalechina/joyful-pandas#9]
hi，每一章的结尾有 问题 和 练习 。我看参考答案那一章只有 练习 的参考答案，但是没有 问题 的参考答案

**Comment by GYHHAHA** [comment]
目前问题部分没有给出参考答案，等到暑假时教程会全面修订，进行部分章节内容的重写和文字/图片的扩充完善，待结构调整后会增加问题部分的参考答案/提示/思路
